version: '3.8'
services:
  kafka:
    image: bitnami/kafka:3.5.0  # Or your Kafka image
    container_name: kafka
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_CFG_METADATA_LOG_DIR=/var/lib/kafka/metadata
      - ALLOW_PLAINTEXT_LISTENER=yes  # Allow PLAINTEXT listener
    ports:
      - "9094:9094"  # External Kafka client access
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-metadata:/var/lib/kafka/metadata
    networks:
      - kafka-network

volumes:
  kafka-data:
  kafka-metadata:

networks:
  kafka-network:
    driver: bridge
