server:
  port: 9098


spring:
  kafka:
    bootstrap-servers: "192.168.138.222:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.LongSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://192.168.138.222:8081"
    streams:
      bootstrap-servers: "192.168.138.222:9092"
      application-id: "spring-kafka-streams-processor-api-stateless-operations-1"
    consumer:
      group-id: "spring-kafka-streams-processor-api-stateless-operations-consumer-1"
      keyDeserializer: "org.apache.kafka.common.serialization.LongDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://192.168.138.222:8081"
        specific:
          avro:
            reader: "true"


schema:
  registry:
    url: "http://192.168.138.222:8081"

topic:
  source:
    name: "loan.detail.avro.topic.v1"
  sink:
    collateral:
      name: "collateral.enriched.detail.avro.topic.v1"
    employment:
      name: "employment.enriched.detail.avro.topic.v1"