version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-kraft
    ports:
      - "9092:9092" # Kafka broker port
      - "9093:9093" # Controller listener port
    environment:
      # KRaft-specific configurations
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1" # Unique node ID for the broker/controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093" # Quorum voters (node ID @ address)
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093" # Listeners for broker and controller
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092" # Address advertised to clients
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT" # Listener used for inter-broker communication
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1" # Single-node setup
    volumes:
      - kafka-data:/var/lib/kafka/data # Persist Kafka data
    networks:
      - kafka-network

volumes:
  kafka-data: # Volume for persisting Kafka logs
    driver: local

networks:
  kafka-network: # Custom Docker network
    driver: bridge
